#!/bin/bash
# https://github.com/tdihp/dspcap
set -e
set -o pipefail
STARTTIME=$(date +%s)
PIDFILE=/var/run/dspcap.pid
NAMESPACE=default
IMAGE="alpine:3.20" # only used for nsenter
TCPDUMP_ARGS="-i any -s 1024"

cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dspcap
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      app: dspcap
  template:
    metadata:
      labels:
        app: dspcap
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: tcpdump
        command:
        - nsenter
        - --
        - sh
        - -xc
        - |
          apk add curl
          mkdir /root/bin
          curl -fsSL https://github.com/mozillazg/ptcpdump/releases/download/v0.24.0/ptcpdump_0.24.0_linux_amd64.tar.gz | tar --directory=/root/bin/ -xzf - ptcpdump
          export PATH="/root/bin:\$PATH"
          mkdir -p /tmp/dspcap
          chmod 777 /tmp/dspcap
          echo "starting pcap"
          ptcpdump $TCPDUMP_ARGS -w "/tmp/dspcap/$STARTTIME.\$(hostname).pcap" &
          echo \$! >$PIDFILE
          wait
          rm $PIDFILE
          echo "sleeping forever"
          sleep infinity
        image: $IMAGE
        resources:
          requests:
            cpu: 50m
            memory: 50M
        securityContext:
          privileged: true
EOF

kubectl rollout status daemonset/dspcap -n $NAMESPACE
echo "Capture started. Use dspcap-stop to stop capture and collect outcome."
